### ISSUE TITLE
[User Manual > The GUI] structure the content into submenus 

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box-documentation#17]
```
The GUI
    Toolbars
          <list all the toolbars>
```
![image](https://user-images.githubusercontent.com/45030715/194826234-cd054bc9-dc4a-41d7-844f-a35352d3d101.png)

```
The GUI
    Toolbars
    Panels
          <list all the panels> (list also the panels that are introduced by apps/tools; e.g. GEE TSE, Profile Analytics, Raster Layer Styling, ...) 
```
![image](https://user-images.githubusercontent.com/45030715/194826943-3bbf2895-74cf-464f-a825-9fd1bc33e380.png)

```
The GUI
    Toolbars
    Panels
    Views
        MapView
        SpectralView
        ... (what else?)
```

**Comment by thielfab** [comment]
So `Data Views` is a panel.
Are the Map/Spectral Library Windows/Views also panels in the end? And what do we call them, Views or Windows?

**Comment by janzandr** [comment]
> Are the Map/Spectral Library Windows/Views also panels in the end? And what do we call them, Views or Windows?

No, MapView and a SpectralView aren't panels.
Here is the full list of all the panels:
![image](https://user-images.githubusercontent.com/45030715/195595071-dd981d83-f87b-4a87-8e97-d6f2fc31c5e6.png)

**Comment by thielfab** [comment]
Ok sounds sound. Then we need to adapt the GUI so that it can not be confused 
![grafik](https://user-images.githubusercontent.com/15610561/195595582-cb36c169-b6e2-45cb-90c7-ad8d3c55c808.png)

**Comment by janzandr** [comment]
Yes, I can do this.

**Comment by thielfab** [comment]
👍 Mind that there are also tooltips where this should then be changed

**Comment by janzandr** [comment]
A global search in all PY and UI files should do it.

**Comment by janzandr** [comment]
I would suggest that this is called an **Attribute Table View**
![image](https://user-images.githubusercontent.com/45030715/195600111-7cc8c0de-0228-440d-9470-e92a3fd75f13.png)

**Comment by janzandr** [comment]
> Then we need to adapt the GUI so that it can not be confused

@thielfab is now fixed on master.
