### ISSUE TITLE
[Installation] embed the hyperEDU installation video

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box-documentation#19]
_Discussed with @thielfab and @henriDierkes ._

Installing the EnMAP-Box for the first time can be challenging.
We need to:
- install QGIS
- install the EnMAP-Box plugin
- install plugin dependencies (e.g. Google Earth Engine)
- install Python dependencies

A video showing all the steps may help new users.

**Comment by thielfab** [comment]
Maybe this is still valid enough? Some minor things here and there have changed, yes. https://www.youtube.com/watch?v=_SNbLmB8aCQ

**Comment by janzandr** [comment]
Oh yes, we take this video!

**Comment by janzandr** [comment]
I'll close this here and create a new issue for embedding all the hyperEDU videos inside the RTD website.
