### ISSUE TITLE
describe how to download EnMAP products from the EnMAP Data Portal

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box-documentation#32]
Add a new menu entry "EnMAP Data Portal" to the GENERAL menu:
![image](https://user-images.githubusercontent.com/45030715/201651843-3d23ac2a-9069-476b-85b4-38a2e1036aee.png)

Describe how to download data. E.g. as descriped here:
https://mastodon.online/@henningbuddenbaum/109323896901791703

**Comment by henriDierkes** [comment]
Added with pull request #33 
Please review! @janzandr @thielfab

**Comment by janzandr** [comment]
Can you send the HTML?

**Comment by thielfab** [comment]
`git remote add henrike git@github.com:henriDierkes/enmap-box-documentation.git`
`git fetch henrike main`
Then you should be able to checkout branch and build

**Comment by thielfab** [comment]
added with [7e183b1](https://github.com/EnMAP-Box/enmap-box-documentation/commit/7e183b1f58417e4b1c0d1b07a27e75ccf2250209)
