### ISSUE TITLE
Update paths to conda environment 

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box-documentation#53]
Currently the [Dev Installation instructions](https://enmap-box.readthedocs.io/en/latest/dev_section/dev_installation.html#e-setup-conda-all-platforms) point to the file `conda_environment.yml` in the enmap-box root folder. Is this file still needed, or is it deprecated by the various options in `.env/conda`?
Another question is, once the installation guide in the user section is updated and also explains conda installation, do we just point to these instructions in the Dev Installation guide to avoid redundancy?

**Comment by janzandr** [comment]
> Currently the [Dev Installation instructions](https://enmap-box.readthedocs.io/en/latest/dev_section/dev_installation.html#e-setup-conda-all-platforms) point to the file conda_environment.yml in the enmap-box root folder. Is this file still needed, or is it deprecated by the various options in .env/conda?

I think it is deprecated.
@jakimowb?

**Comment by janzandr** [comment]
> Another question is, once the installation guide in the user section is updated and also explains conda installation, do we just point to these instructions in the Dev Installation guide to avoid redundancy?

I would say yes (if nothing speaks against it).

**Comment by janzandr** [comment]
done

**Comment by jakimowb** [comment]
@janzandr have you already pushed your changes that removed the redundant installation descriptions?
