### ISSUE TITLE
Update known issues link

### ISSUE THREAD

**Issue by thielfab** [EnMAP-Box/enmap-box-documentation#6]
@janzandr This link under known issues is not valid anymore:
https://enmap-box.readthedocs.io/en/latest/general/faq_trouble.html#known-issues
Do we have something similar in the new github issue tracker?

**Comment by janzandr** [comment]
This looks wrong:
![image](https://user-images.githubusercontent.com/45030715/189671793-ad7d873d-08ca-4685-9cb7-26ff9ace5a2e.png)

Did somebody run a global replace Bitbucket with GitHub?

**Comment by thielfab** [comment]
Yes, pretty much. But not me.
The question is whether we want to point to the old bitbucket issue tracker here?

**Comment by janzandr** [comment]
Yes. The old tracker is still in use, and the old link is still valid.
So far, we don't have "known issues" inside the GitLab tracker.

**Comment by janzandr** [comment]
Thanks. I just changed the color to red.
