### ISSUE TITLE
[README] provide fully qualified URL to the requirements.txt file

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box-documentation#65]
FYI @jakimowb, it is proposed to show the install pip command using the fully specified URL to allow copy&paste approach for installation.
![image](https://github.com/EnMAP-Box/enmap-box-documentation/assets/45030715/5c8fd859-b075-4896-848e-4b4865fc5763)

**Comment by janzandr** [comment]
URL is
https://raw.githubusercontent.com/EnMAP-Box/enmap-box-documentation/main/requirements.txt

**Comment by jakimowb** [comment]
Such minor modification don't need an issue. Just change it :-)
