### ISSUE TITLE
EnGeoMAP tutorial out of date

### ISSUE THREAD

**Issue by grantboxer** [EnMAP-Box/enmap-box-documentation#8]
I have been trying to work my way through the tutorial for EnGeoMap but the description in the tutorial does not match what I see in the EnGeoMAP version (v3). I know updating documentation can be a pain but it would be really appreciated if you can find the time to update the tutorials to match the current versions of the software.
Great piece of software and really keen to try it out in real mineral exploration situations.
Regards Grant Boxer, Perth, Western Australia

**Comment by jakimowb** [comment]
@janzandr I just wondered why you have closed this issue. We need to keep it open until the documentation fits to the GUI.

**Comment by janzandr** [comment]
Just a misunderstanding. 
I thought you already posted the link to the new, overhauled version :-)

**Comment by janzandr** [comment]
@jakimowb  to my knowledge, Helge is still working on a new version of the tutorial.
@thielfab  do you know more?

**Comment by hdaemp** [comment]
Hi, I just edited a fork and did a pull request for the new EnGeoMAP 3.1 tutorial.

**Comment by grantboxer** [comment]
Excellent. Will the web site now reference the update yet?

**Comment by thielfab** [comment]
PR merged ([cf9ea54](https://github.com/EnMAP-Box/enmap-box-documentation/commit/cf9ea54db01a0440ba9409157ca59ddd007a5594)) and new tutorial should be up now!
